-- MySQL Script generated by MySQL Workbench
-- 03/07/16 09:06:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aptizaProfesor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aptizaProfesor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aptizaProfesor` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `aptizaProfesor` ;

-- -----------------------------------------------------
-- Table `aptizaProfesor`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`profesor` (
  `EMAIL` VARCHAR(60) NOT NULL,
  `DNI` VARCHAR(9) NULL,
  `NOMBRE` VARCHAR(20) NULL,
  `APELLIDOS` VARCHAR(50) NULL,
  `NRP` VARCHAR(20) NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`curso` (
  `IDCURSO` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IDCURSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`grupo` (
  `IDGRUPO` VARCHAR(30) NOT NULL,
  `curso_IDCURSO` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IDGRUPO`, `curso_IDCURSO`),
  INDEX `fk_aptizagrupo_curso1_idx` (`curso_IDCURSO` ASC),
  CONSTRAINT `fk_aptizagrupo_curso1`
    FOREIGN KEY (`curso_IDCURSO`)
    REFERENCES `aptizaProfesor`.`curso` (`IDCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`alumno` (
  `EMAIL` VARCHAR(60) NOT NULL,
  `DNI` VARCHAR(9) NULL,
  `NOMBRE` VARCHAR(20) NULL,
  `APELLIDOS` VARCHAR(50) NULL,
  PRIMARY KEY (`EMAIL`))
ENGINE = InnoDB
COMMENT = '				';


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`asignatura` (
  `MATERIA` VARCHAR(30) NOT NULL,
  `DESCRIPCION` VARCHAR(500) NULL,
  `ABREVIATURA` VARCHAR(10) NULL,
  PRIMARY KEY (`MATERIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`unidad` (
  `IDUNIDAD` VARCHAR(30) NOT NULL,
  `TUTOR` VARCHAR(30) NULL,
  `asignatura_MATERIA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IDUNIDAD`, `asignatura_MATERIA`),
  INDEX `fk_aptizaunidad_asignatura1_idx` (`asignatura_MATERIA` ASC),
  CONSTRAINT `fk_aptizaunidad_asignatura1`
    FOREIGN KEY (`asignatura_MATERIA`)
    REFERENCES `aptizaProfesor`.`asignatura` (`MATERIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`actividad` (
  `IDACTIVIDAD` VARCHAR(30) NOT NULL,
  `NOMBRE` VARCHAR(20) NULL,
  `DESCRIPCION` VARCHAR(500) NULL,
  `unidad_IDUNIDAD` VARCHAR(30) NOT NULL,
  `unidad_asignatura_MATERIA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IDACTIVIDAD`, `unidad_IDUNIDAD`, `unidad_asignatura_MATERIA`),
  INDEX `fk_aptizaactividad_unidad1_idx` (`unidad_IDUNIDAD` ASC, `unidad_asignatura_MATERIA` ASC),
  CONSTRAINT `fk_aptizaactividad_unidad1`
    FOREIGN KEY (`unidad_IDUNIDAD` , `unidad_asignatura_MATERIA`)
    REFERENCES `aptizaProfesor`.`unidad` (`IDUNIDAD` , `asignatura_MATERIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`da_clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`da_clase` (
  `profesor_EMAIL` VARCHAR(60) NOT NULL,
  `grupo_IDGRUPO` VARCHAR(30) NOT NULL,
  `ES_TUTOR` VARCHAR(30) NULL,
  PRIMARY KEY (`profesor_EMAIL`, `grupo_IDGRUPO`),
  INDEX `fk_aptizaprofesor_has_grupo_grupo1_idx` (`grupo_IDGRUPO` ASC),
  INDEX `fk_aptizaprofesor_has_grupo_profesor_idx` (`profesor_EMAIL` ASC),
  CONSTRAINT `fk_aptizaprofesor_has_grupo_profesor`
    FOREIGN KEY (`profesor_EMAIL`)
    REFERENCES `aptizaProfesor`.`profesor` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aptizaprofesor_has_grupo_grupo1`
    FOREIGN KEY (`grupo_IDGRUPO`)
    REFERENCES `aptizaProfesor`.`grupo` (`IDGRUPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`esta_compuesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`esta_compuesto` (
  `grupo_IDGRUPO` VARCHAR(30) NOT NULL,
  `alumno_EMAIL` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`grupo_IDGRUPO`, `alumno_EMAIL`),
  INDEX `fk_aptizagrupo_has_alumno_alumno1_idx` (`alumno_EMAIL` ASC),
  INDEX `fk_aptizagrupo_has_alumno_grupo1_idx` (`grupo_IDGRUPO` ASC),
  CONSTRAINT `fk_aptizagrupo_has_alumno_grupo1`
    FOREIGN KEY (`grupo_IDGRUPO`)
    REFERENCES `aptizaProfesor`.`grupo` (`IDGRUPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aptizagrupo_has_alumno_alumno1`
    FOREIGN KEY (`alumno_EMAIL`)
    REFERENCES `aptizaProfesor`.`alumno` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`se_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`se_matricula` (
  `alumno_EMAIL` VARCHAR(60) NOT NULL,
  `asignatura_MATERIA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`alumno_EMAIL`, `asignatura_MATERIA`),
  INDEX `fk_aptizaalumno_has_asignatura_asignatura1_idx` (`asignatura_MATERIA` ASC),
  INDEX `fk_aptizaalumno_has_asignatura_alumno1_idx` (`alumno_EMAIL` ASC),
  CONSTRAINT `fk_aptizaalumno_has_asignatura_alumno1`
    FOREIGN KEY (`alumno_EMAIL`)
    REFERENCES `aptizaProfesor`.`alumno` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aptizaalumno_has_asignatura_asignatura1`
    FOREIGN KEY (`asignatura_MATERIA`)
    REFERENCES `aptizaProfesor`.`asignatura` (`MATERIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`imparte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`imparte` (
  `profesor_EMAIL` VARCHAR(60) NOT NULL,
  `asignatura_MATERIA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`profesor_EMAIL`, `asignatura_MATERIA`),
  INDEX `fk_aptizaprofesor_has_asignatura_asignatura1_idx` (`asignatura_MATERIA` ASC),
  INDEX `fk_aptizaprofesor_has_asignatura_profesor1_idx` (`profesor_EMAIL` ASC),
  CONSTRAINT `fk_aptizaprofesor_has_asignatura_profesor1`
    FOREIGN KEY (`profesor_EMAIL`)
    REFERENCES `aptizaProfesor`.`profesor` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aptizaprofesor_has_asignatura_asignatura1`
    FOREIGN KEY (`asignatura_MATERIA`)
    REFERENCES `aptizaProfesor`.`asignatura` (`MATERIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`da`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`da` (
  `profesor_EMAIL` VARCHAR(60) NOT NULL,
  `unidad_IDUNIDAD` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`profesor_EMAIL`, `unidad_IDUNIDAD`),
  INDEX `fk_aptizaprofesor_has_unidad_unidad1_idx` (`unidad_IDUNIDAD` ASC),
  INDEX `fk_aptizaprofesor_has_unidad_profesor1_idx` (`profesor_EMAIL` ASC),
  CONSTRAINT `fk_aptizaprofesor_has_unidad_profesor1`
    FOREIGN KEY (`profesor_EMAIL`)
    REFERENCES `aptizaProfesor`.`profesor` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aptizaprofesor_has_unidad_unidad1`
    FOREIGN KEY (`unidad_IDUNIDAD`)
    REFERENCES `aptizaProfesor`.`unidad` (`IDUNIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`realiza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`realiza` (
  `profesor_EMAIL` VARCHAR(60) NOT NULL,
  `actividad_IDACTIVIDAD` VARCHAR(30) NOT NULL,
  `FECHAINICIO` DATE NULL,
  `FECHAFIN` DATE NULL,
  PRIMARY KEY (`profesor_EMAIL`, `actividad_IDACTIVIDAD`),
  INDEX `fk_aptizaprofesor_has_actividad_actividad1_idx` (`actividad_IDACTIVIDAD` ASC),
  INDEX `fk_aptizaprofesor_has_actividad_profesor1_idx` (`profesor_EMAIL` ASC),
  CONSTRAINT `fk_aptizaprofesor_has_actividad_profesor1`
    FOREIGN KEY (`profesor_EMAIL`)
    REFERENCES `aptizaProfesor`.`profesor` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aptizaprofesor_has_actividad_actividad1`
    FOREIGN KEY (`actividad_IDACTIVIDAD`)
    REFERENCES `aptizaProfesor`.`actividad` (`IDACTIVIDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aptizaProfesor`.`se_da`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aptizaProfesor`.`se_da` (
  `curso_IDCURSO` VARCHAR(30) NOT NULL,
  `asignatura_MATERIA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`curso_IDCURSO`, `asignatura_MATERIA`),
  INDEX `fk_aptizacurso_has_asignatura_asignatura1_idx` (`asignatura_MATERIA` ASC),
  INDEX `fk_aptizacurso_has_asignatura_curso1_idx` (`curso_IDCURSO` ASC),
  CONSTRAINT `fk_aptizacurso_has_asignatura_curso1`
    FOREIGN KEY (`curso_IDCURSO`)
    REFERENCES `aptizaProfesor`.`curso` (`IDCURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aptizacurso_has_asignatura_asignatura1`
    FOREIGN KEY (`asignatura_MATERIA`)
    REFERENCES `aptizaProfesor`.`asignatura` (`MATERIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
